name: End-to-End Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*
      - fix/*

jobs:
  e2e-test-pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        country: [us, jp]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Clean up previous run artifacts
        run: rm -rf BigCatalogRawData/ AllRawData/ UlAdd/

      - name: STEP 1: Scrape live data (Test Mode)
        run: python main.py giant ${{ matrix.country }} --limit=10 --test-run

      - name: STEP 2: Enrich scraped data (Test Mode)
        run: python main.py enrich_catalogs 20250101 --limit=10 --test-run

      - name: Verify enriched output file exists
        run: |
          FILE_PATH="UlAdd/test-catalog_all_UlAdd_20250101.json"
          if [ -f "$FILE_PATH" ]; then
            echo "SUCCESS: Enriched file found at $FILE_PATH"
          else
            echo "ERROR: Enriched file not found at $FILE_PATH"
            exit 1
          fi

      - name: Upload Enriched Artifact
        uses: actions/upload-artifact@v4
        with:
          name: enriched-data-${{ matrix.country }}
          path: UlAdd/test-catalog_all_UlAdd_20250101.json
          if-no-files-found: error