name: Scrape App Store Rankings

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        country: [us, jp, cn, kr, in, gb, fr, sg, ru]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper for Giant Catalog
        run: python main.py giant ${{ matrix.country }}

      - name: Run scraper for Supplement Catalog
        run: python main.py supplement ${{ matrix.country }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: raw-data-${{ matrix.country }}
          path: |
            BigCatalogRawData/
            SupplementCatalogRawData/
          if-no-files-found: error

  commit:
    runs-on: ubuntu-latest
    needs: scrape
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./
          pattern: raw-data-*
          merge-multiple: true

      - name: List files for debugging
        run: ls -lR

      - name: Commit and push if files changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: Update app rankings data for multiple countries'
          file_pattern: 'BigCatalogRawData/*.json SupplementCatalogRawData/*.json'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'