name: Scrape App Store Rankings

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper for Giant Catalog (JP)
        run: python main.py giant jp

      - name: Run scraper for Supplement Catalog (JP)
        run: python main.py supplement jp

      # Note: To add more countries, add more run steps for each mode.
      # Example:
      # - name: Run scraper for Giant Catalog (US)
      #   run: python main.py giant us
      # - name: Run scraper for Supplement Catalog (US)
      #   run: python main.py supplement us

      - name: Commit and push if files changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: Update app rankings data'
          file_pattern: 'BigCatalogRawData/*.json SupplementCatalogRawData/*.json'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'